Feature/deploy on coolify
savicsoft/mvp-experiment-server pull request #17
Opened 2023-10-31 07:44 UTC by Caaki

Changed to use all public routes to test on server.

2023-11-02 12:08 UTC, savicsoft approved these changes

2023-11-07 13:57 UTC, lardezzoni requested changes
The codehave conflitcts with new merges, it has to be updated. In application-dev.properties there are issues with the /dev branch in what user and password for postgres to use.

2023-11-08 09:36 UTC, AhmedI999 approved these changes

2023-11-08 09:37 UTC, d-grytsyna approved these changes

2023-11-08 09:37 UTC, lardezzoni approved these changes
Ok

2023-11-08 09:37 UTC, merged